site_name: PropperBot
site_author: Popper Family
site_url: https://github.com/jodylecompte/PopperBot
copyright: 'Â© 2020 Popper Family MIT'
nav:
  - Home: index.md
  - Commands: commands.md
  - Changelog: changelog.md
  - License: LICENSE.md

theme:
  palette:
    scheme: slate
    primary: teal
  name: material
  font: false
  feature:
    tabs: true
  favicon: https://avatars3.githubusercontent.com/u/6692364?s=400&u=ac3000ec9ec40db490ab01953f05f2933d7b037f&v=4

  markdown_extensions:
    - plantuml_markdown:
        server: http://www.plantuml.com/plantuml 
    - markdown_checklist.extension

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/6tbuesB